# backend/app/api/v1/endpoints/sharing.py
from fastapi import APIRouter, Depends, Path
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.dependencies import get_current_user, get_db
from app.core.exceptions import AuthorizationError, ResourceNotFoundError
from app.core.permissions import verify_parent_access
from app.crud.sharing import ShareRepository
from app.helpers.response_builder import build_response
from app.models.user import User
from app.schemas.common import ApiResponse
from app.schemas.sharing import DoctorBriefResponse, DoctorShareCreate, DoctorShareResponse
from app.services.sharing_service import SharingService

router = APIRouter(prefix="/sharing", tags=["Doctor Sharing & Briefs"])


@router.post("/doctor-token", response_model=ApiResponse[DoctorShareResponse])
async def create_doctor_share_token(
    data: DoctorShareCreate,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_db),
):
    _, member = await verify_parent_access(session, current_user.id, data.parent_id)
    if not member.can_share_doctor_brief:
        raise AuthorizationError("Doctor brief sharing permission is required.")
    service = SharingService(session)
    share = await service.create_doctor_share(
        parent_id=data.parent_id,
        user_id=current_user.id,
        share_scope=data.share_scope.value,
        expires_in_hours=data.expires_in_hours,
    )
    return build_response(DoctorShareResponse.model_validate(share))


@router.get("/doctor-brief/{token}", response_model=ApiResponse[DoctorBriefResponse])
async def get_doctor_brief_by_share_token(
    token: str = Path(..., description="Expiring share token generated by family member"),
    session: AsyncSession = Depends(get_db),
):
    service = SharingService(session)
    brief = await service.get_doctor_brief_by_token(token)
    return build_response(brief)


@router.post("/revoke/{token}", response_model=ApiResponse[dict])
async def revoke_doctor_share_token(
    token: str,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_db),
):
    repo = ShareRepository(session)
    share = await repo.get_by_token(token)
    if not share:
        raise ResourceNotFoundError("ShareToken", token)
    _, member = await verify_parent_access(session, current_user.id, share.parent_id)
    if share.created_by != current_user.id and not member.can_share_doctor_brief:
        raise AuthorizationError("You cannot revoke this doctor share.")
    await repo.update(share.id, is_revoked=True)
    return build_response({"status": "revoked", "token": token})
